// System.screen{Width,Height}¤ÎÊË˜”¤ò‰ä¸ü¤¹¤ë

Krkr2CompatUtils.require("deskinfo");

property _System_screenWidth  { getter { return _System_primary_getMonitorInfo("screenWidth",  "monitor", "w"); } }
property _System_screenHeight { getter { return _System_primary_getMonitorInfo("screenHeight", "monitor", "h"); } }

&System.screenWidth  = &_System_screenWidth;
&System.screenHeight = &_System_screenHeight;

eight;

